# Site settings
title: Karin Sandstrom 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url:  "http://karinsandstrom.github.io" # "http://localhost:4000" # 
twitter_username: karinsandstrom 
github_username:  karinsandstrom

# Build settings
markdown: kramdown
